name: Build site
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'repo'

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build Hakyll
        run: |
          cd repo
          nix-build

      - name: Build site
        run: |
          repo/result/bin/site build
